### GET /
GET http://localhost:5003
### POST REGISTER
POST  http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "john",
    "password": "134"
}
### POST LOGIN
POST  http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "john",
    "password": "134"
}

### Fetch all todos GET /TODOS (protected) 
GET http://localhost:5003/todos 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgzOTYzMzE2LCJleHAiOjE3ODQwNDk3MTZ9.dk5WKtzLI-ZOCnI5rMH0-8mdr-EJctvw1yM6Q2Fl-aA
### Post a  todos POST /TODOS (protected) 
POST http://localhost:5003/todos 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgzOTYzMzE2LCJleHAiOjE3ODQwNDk3MTZ9.dk5WKtzLI-ZOCnI5rMH0-8mdr-EJctvw1yM6Q2Fl-aA
Content-Type: application/json

{
    "task": "test"
}
### PUT a  todos PUT /TODOS/:ID (protected) 
PUT http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgzOTYzMzE2LCJleHAiOjE3ODQwNDk3MTZ9.dk5WKtzLI-ZOCnI5rMH0-8mdr-EJctvw1yM6Q2Fl-aA
Content-Type: application/json

{
    "completed": 1
}
### DELETE a  todos DELETE /TODOS/:ID (protected) 
DELETE http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgzOTYzMzE2LCJleHAiOjE3ODQwNDk3MTZ9.dk5WKtzLI-ZOCnI5rMH0-8mdr-EJctvw1yM6Q2Fl-aA
